export const Users = [
  {
    id:1,
    profilePicture: "1.jpg",
    username: "Safak Kocaoglu",
  },
  {
    id:2,
    profilePicture: "2.jpg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "3.jpg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "4.jpg",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "5.jpg",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "7.jpg",
    username: "Travis Bennett",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpg",
    date: "3 days ago",
    userId: 7,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpg",
    date: "5 days ago",
    userId: 5,
    like: 11,
    comment: 2,
  },
 
];